// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using partymanager.Infrastructure.Data.Context;

#nullable disable

namespace partymanager.Infrastructure.Data.Migrations
{
    [DbContext(typeof(SqlServerContext))]
    [Migration("20240926164711_AddLocalidadeToEvento")]
    partial class AddLocalidadeToEvento
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("partymanager.Domain.Entidades.Evento", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<decimal>("aluguelEspaco")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("data")
                        .HasColumnType("datetime2");

                    b.Property<int>("idTipoEvento")
                        .HasColumnType("int");

                    b.Property<int?>("idUsuario")
                        .HasColumnType("int");

                    b.Property<string>("localidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("numeroAdultos")
                        .HasColumnType("int");

                    b.Property<int>("numeroCriancas")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("idTipoEvento");

                    b.HasIndex("idUsuario");

                    b.ToTable("evento");
                });

            modelBuilder.Entity("partymanager.Domain.Entidades.Item", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("idTipoItem")
                        .HasColumnType("int");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("precoUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("id");

                    b.HasIndex("idTipoItem");

                    b.ToTable("item");
                });

            modelBuilder.Entity("partymanager.Domain.Entidades.ItemCalculado", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("idEvento")
                        .HasColumnType("int");

                    b.Property<int>("idItem")
                        .HasColumnType("int");

                    b.Property<decimal>("precoAproximado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("quantidade")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("id");

                    b.HasIndex("idEvento");

                    b.HasIndex("idItem");

                    b.ToTable("itemcalculado");
                });

            modelBuilder.Entity("partymanager.Domain.Entidades.TipoEvento", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id");

                    b.ToTable("tipoevento");
                });

            modelBuilder.Entity("partymanager.Domain.Entidades.TipoEventoItem", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("idItem")
                        .HasColumnType("int");

                    b.Property<int>("idTipoEvento")
                        .HasColumnType("int");

                    b.Property<decimal>("quantidadePorPessoa")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("id");

                    b.HasIndex("idItem");

                    b.HasIndex("idTipoEvento");

                    b.ToTable("tipoeventoitem");
                });

            modelBuilder.Entity("partymanager.Domain.Entidades.TipoItem", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id");

                    b.ToTable("tipoitem");
                });

            modelBuilder.Entity("partymanager.Domain.Entidades.Usuario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("id");

                    b.ToTable("usuario");
                });

            modelBuilder.Entity("partymanager.Domain.Entidades.Evento", b =>
                {
                    b.HasOne("partymanager.Domain.Entidades.TipoEvento", "tipoevento")
                        .WithMany("evento")
                        .HasForeignKey("idTipoEvento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("partymanager.Domain.Entidades.Usuario", "usuario")
                        .WithMany("evento")
                        .HasForeignKey("idUsuario")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("tipoevento");

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("partymanager.Domain.Entidades.Item", b =>
                {
                    b.HasOne("partymanager.Domain.Entidades.TipoItem", "tipoitem")
                        .WithMany("item")
                        .HasForeignKey("idTipoItem")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("tipoitem");
                });

            modelBuilder.Entity("partymanager.Domain.Entidades.ItemCalculado", b =>
                {
                    b.HasOne("partymanager.Domain.Entidades.Evento", "evento")
                        .WithMany("itemcalculado")
                        .HasForeignKey("idEvento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("partymanager.Domain.Entidades.Item", "item")
                        .WithMany("itemcalculado")
                        .HasForeignKey("idItem")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("evento");

                    b.Navigation("item");
                });

            modelBuilder.Entity("partymanager.Domain.Entidades.TipoEventoItem", b =>
                {
                    b.HasOne("partymanager.Domain.Entidades.Item", "item")
                        .WithMany("tipoeventoitem")
                        .HasForeignKey("idItem")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("partymanager.Domain.Entidades.TipoEvento", "tipoevento")
                        .WithMany("tipoeventoitem")
                        .HasForeignKey("idTipoEvento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("item");

                    b.Navigation("tipoevento");
                });

            modelBuilder.Entity("partymanager.Domain.Entidades.Evento", b =>
                {
                    b.Navigation("itemcalculado");
                });

            modelBuilder.Entity("partymanager.Domain.Entidades.Item", b =>
                {
                    b.Navigation("itemcalculado");

                    b.Navigation("tipoeventoitem");
                });

            modelBuilder.Entity("partymanager.Domain.Entidades.TipoEvento", b =>
                {
                    b.Navigation("evento");

                    b.Navigation("tipoeventoitem");
                });

            modelBuilder.Entity("partymanager.Domain.Entidades.TipoItem", b =>
                {
                    b.Navigation("item");
                });

            modelBuilder.Entity("partymanager.Domain.Entidades.Usuario", b =>
                {
                    b.Navigation("evento");
                });
#pragma warning restore 612, 618
        }
    }
}
